//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartamente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartamente()
        {
            this.Agent_Termic = new HashSet<Agent_Termic>();
            this.ApaCalda = new HashSet<ApaCalda>();
            this.ApaRece = new HashSet<ApaRece>();
            this.Canalizare = new HashSet<Canalizare>();
            this.Contracte_Individuale = new HashSet<Contracte_Individuale>();
            this.EnergieElectrica = new HashSet<EnergieElectrica>();
            this.EnergieElecrica_pe_scara = new HashSet<EnergieElecrica_pe_scara>();
            this.Gaz = new HashSet<Gaz>();
            this.Lift = new HashSet<Lift>();
            this.Salubritate = new HashSet<Salubritate>();
            this.Salarii_Angajati = new HashSet<Salarii_Angajati>();
            this.Curatenie = new HashSet<Curatenie>();
            this.Cota_Parte = new HashSet<Cota_Parte>();
            this.Facturi_Clienti = new HashSet<Facturi_Clienti>();
            this.Fond_Rulment = new HashSet<Fond_Rulment>();
            this.Locatari = new HashSet<Locatari>();
            this.Fond_Reparatii = new HashSet<Fond_Reparatii>();
        }
    
        public int Numar { get; set; }
        public int IdProprietar { get; set; }
        public int Suprafata_mP_ { get; set; }
        public int Suprafata_utila_mP_ { get; set; }
        public int Numar_locatari { get; set; }
        public int Numar_Camere { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agent_Termic> Agent_Termic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApaCalda> ApaCalda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApaRece> ApaRece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Canalizare> Canalizare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracte_Individuale> Contracte_Individuale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergieElectrica> EnergieElectrica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergieElecrica_pe_scara> EnergieElecrica_pe_scara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gaz> Gaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lift> Lift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salubritate> Salubritate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salarii_Angajati> Salarii_Angajati { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curatenie> Curatenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cota_Parte> Cota_Parte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturi_Clienti> Facturi_Clienti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fond_Rulment> Fond_Rulment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locatari> Locatari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fond_Reparatii> Fond_Reparatii { get; set; }
        public virtual Membri_Asociatie Membri_Asociatie { get; set; }
    }
}
