//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avansuri_de_Plata
    {
        public int Index { get; set; }
        public int IdMembru { get; set; }
        public decimal Avansuri { get; set; }
    
        public virtual Membri_Asociatie Membri_Asociatie { get; set; }
    }
}
