//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cota_Parte
    {
        public int Index { get; set; }
        public int IdApartament { get; set; }
        public double Cota_Parte_Agent_termic { get; set; }
        public double Cota_Parte_Canalizare { get; set; }
        public double Cota_Parte_Alte_Servicii { get; set; }
    
        public virtual Apartamente Apartamente { get; set; }
    }
}
