//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturi_Clienti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturi_Clienti()
        {
            this.Restante = new HashSet<Restante>();
        }
    
        public decimal ID { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public int IdApartament { get; set; }
        public decimal Total_de_Plata { get; set; }
        public System.DateTime Data_emitere { get; set; }
        public System.DateTime Data_Scadenta { get; set; }
        public int Perioada_Facturare { get; set; }
        public string Achitat { get; set; }
        public Nullable<System.DateTime> Data_Achitare { get; set; }
    
        public virtual Apartamente Apartamente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restante> Restante { get; set; }
    }
}
