//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturi_Furnizori
    {
        public decimal ID { get; set; }
        public decimal CUIFurnizor { get; set; }
        public decimal Cantitate_furnizata { get; set; }
        public decimal Total_plata { get; set; }
        public System.DateTime Data_emitere { get; set; }
        public System.DateTime Data_scadenta { get; set; }
        public string Perioada_facturare { get; set; }
        public string Achitat { get; set; }
        public System.DateTime Data_Achitare { get; set; }
    
        public virtual Furnizori Furnizori { get; set; }
    }
}
