//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juranal
    {
        public int Index { get; set; }
        public decimal CUIFactura { get; set; }
        public string Tranzactie { get; set; }
        public System.DateTime Data { get; set; }
    }
}
