//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restante
    {
        public int Index { get; set; }
        public decimal CUIFactura { get; set; }
        public decimal Restante1 { get; set; }
        public int Penalizari_zi { get; set; }
        public int Zile_de_penalizare { get; set; }
        public string Data_curenta { get; set; }
        public string Data_scadenta { get; set; }
    
        public virtual Facturi_Clienti Facturi_Clienti { get; set; }
    }
}
