//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venituri
    {
        public int Index { get; set; }
        public Nullable<decimal> Fond_Servicii { get; set; }
        public Nullable<decimal> Fond_rulment { get; set; }
        public Nullable<decimal> Fond_reparatii { get; set; }
    }
}
